name: online_course
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  timeago: ^3.7.0
  http_interceptor: ^2.0.0
  app_links: ^6.3.3
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.16
  cached_network_image: ^3.1.0
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  chewie: ^1.8.5
  video_player: ^2.8.2
  url_launcher: ^6.3.1
  screen_protector: ^1.4.2+1
  visibility_detector: ^0.4.0+2
  flutter_localizations:
    sdk: flutter
  intl: any
  image_picker: ^1.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  generate: true # Add this line
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/categories/
    - assets/logo.png
    - assets/images/
    - .env.development
    - .env.production
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-VariableFont_wght.ttf
        - asset: fonts/Rubik-Italic-VariableFont_wght.ttf
          style: italic
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/Rubik-Black.ttf
          weight: 900
